env:
  es2021: true
  node: true
extends: airbnb-base
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: 
  no-console: off
  import/extensions: off
  no-continue: off
  no-underscore-dangle: off
